SELECT * FROM banco
SELECT * FROM deposito
SELECT * FROM guia
SELECT * FROM producto

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE guia;
TRUNCATE TABLE producto;
TRUNCATE TABLE deposito;
SET FOREIGN_KEY_CHECKS = 1;
