// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: despacho.proto

package despachopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DespachoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransportistaId int32                  `protobuf:"varint,1,opt,name=transportista_id,json=transportistaId,proto3" json:"transportista_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DespachoRequest) Reset() {
	*x = DespachoRequest{}
	mi := &file_despacho_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DespachoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DespachoRequest) ProtoMessage() {}

func (x *DespachoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_despacho_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DespachoRequest.ProtoReflect.Descriptor instead.
func (*DespachoRequest) Descriptor() ([]byte, []int) {
	return file_despacho_proto_rawDescGZIP(), []int{0}
}

func (x *DespachoRequest) GetTransportistaId() int32 {
	if x != nil {
		return x.TransportistaId
	}
	return 0
}

type EntregaResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mensaje          string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	TotalRegistradas int32                  `protobuf:"varint,2,opt,name=total_registradas,json=totalRegistradas,proto3" json:"total_registradas,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EntregaResponse) Reset() {
	*x = EntregaResponse{}
	mi := &file_despacho_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaResponse) ProtoMessage() {}

func (x *EntregaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_despacho_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaResponse.ProtoReflect.Descriptor instead.
func (*EntregaResponse) Descriptor() ([]byte, []int) {
	return file_despacho_proto_rawDescGZIP(), []int{1}
}

func (x *EntregaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *EntregaResponse) GetTotalRegistradas() int32 {
	if x != nil {
		return x.TotalRegistradas
	}
	return 0
}

type Guia struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Numero         string                 `protobuf:"bytes,1,opt,name=numero,proto3" json:"numero,omitempty"`
	Fecha          string                 `protobuf:"bytes,2,opt,name=fecha,proto3" json:"fecha,omitempty"` // formato: "2025-07-01"
	CodigoCliente  string                 `protobuf:"bytes,3,opt,name=codigo_cliente,json=codigoCliente,proto3" json:"codigo_cliente,omitempty"`
	NombreCliente  string                 `protobuf:"bytes,4,opt,name=nombre_cliente,json=nombreCliente,proto3" json:"nombre_cliente,omitempty"`
	NroComprobante string                 `protobuf:"bytes,5,opt,name=nro_comprobante,json=nroComprobante,proto3" json:"nro_comprobante,omitempty"`
	ImporteXCobrar float64                `protobuf:"fixed64,6,opt,name=importe_x_cobrar,json=importeXCobrar,proto3" json:"importe_x_cobrar,omitempty"`
	MontoCobrado   float64                `protobuf:"fixed64,7,opt,name=monto_cobrado,json=montoCobrado,proto3" json:"monto_cobrado,omitempty"`
	Entregada      bool                   `protobuf:"varint,8,opt,name=entregada,proto3" json:"entregada,omitempty"`
	Productos      []*Producto            `protobuf:"bytes,9,rep,name=productos,proto3" json:"productos,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Guia) Reset() {
	*x = Guia{}
	mi := &file_despacho_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guia) ProtoMessage() {}

func (x *Guia) ProtoReflect() protoreflect.Message {
	mi := &file_despacho_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guia.ProtoReflect.Descriptor instead.
func (*Guia) Descriptor() ([]byte, []int) {
	return file_despacho_proto_rawDescGZIP(), []int{2}
}

func (x *Guia) GetNumero() string {
	if x != nil {
		return x.Numero
	}
	return ""
}

func (x *Guia) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *Guia) GetCodigoCliente() string {
	if x != nil {
		return x.CodigoCliente
	}
	return ""
}

func (x *Guia) GetNombreCliente() string {
	if x != nil {
		return x.NombreCliente
	}
	return ""
}

func (x *Guia) GetNroComprobante() string {
	if x != nil {
		return x.NroComprobante
	}
	return ""
}

func (x *Guia) GetImporteXCobrar() float64 {
	if x != nil {
		return x.ImporteXCobrar
	}
	return 0
}

func (x *Guia) GetMontoCobrado() float64 {
	if x != nil {
		return x.MontoCobrado
	}
	return 0
}

func (x *Guia) GetEntregada() bool {
	if x != nil {
		return x.Entregada
	}
	return false
}

func (x *Guia) GetProductos() []*Producto {
	if x != nil {
		return x.Productos
	}
	return nil
}

type Producto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Cantidad      int32                  `protobuf:"varint,2,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producto) Reset() {
	*x = Producto{}
	mi := &file_despacho_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producto) ProtoMessage() {}

func (x *Producto) ProtoReflect() protoreflect.Message {
	mi := &file_despacho_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producto.ProtoReflect.Descriptor instead.
func (*Producto) Descriptor() ([]byte, []int) {
	return file_despacho_proto_rawDescGZIP(), []int{3}
}

func (x *Producto) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Producto) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

var File_despacho_proto protoreflect.FileDescriptor

const file_despacho_proto_rawDesc = "" +
	"\n" +
	"\x0edespacho.proto\x12\bdespacho\"<\n" +
	"\x0fDespachoRequest\x12)\n" +
	"\x10transportista_id\x18\x01 \x01(\x05R\x0ftransportistaId\"X\n" +
	"\x0fEntregaResponse\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12+\n" +
	"\x11total_registradas\x18\x02 \x01(\x05R\x10totalRegistradas\"\xca\x02\n" +
	"\x04Guia\x12\x16\n" +
	"\x06numero\x18\x01 \x01(\tR\x06numero\x12\x14\n" +
	"\x05fecha\x18\x02 \x01(\tR\x05fecha\x12%\n" +
	"\x0ecodigo_cliente\x18\x03 \x01(\tR\rcodigoCliente\x12%\n" +
	"\x0enombre_cliente\x18\x04 \x01(\tR\rnombreCliente\x12'\n" +
	"\x0fnro_comprobante\x18\x05 \x01(\tR\x0enroComprobante\x12(\n" +
	"\x10importe_x_cobrar\x18\x06 \x01(\x01R\x0eimporteXCobrar\x12#\n" +
	"\rmonto_cobrado\x18\a \x01(\x01R\fmontoCobrado\x12\x1c\n" +
	"\tentregada\x18\b \x01(\bR\tentregada\x120\n" +
	"\tproductos\x18\t \x03(\v2\x12.despacho.ProductoR\tproductos\">\n" +
	"\bProducto\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x1a\n" +
	"\bcantidad\x18\x02 \x01(\x05R\bcantidad2\x91\x01\n" +
	"\x0fDespachoService\x12=\n" +
	"\x0eEnviarEntregas\x12\x0e.despacho.Guia\x1a\x19.despacho.EntregaResponse(\x01\x12?\n" +
	"\x10ObtenerDespachos\x12\x19.despacho.DespachoRequest\x1a\x0e.despacho.Guia0\x01B\x0eZ\f./despachopbb\x06proto3"

var (
	file_despacho_proto_rawDescOnce sync.Once
	file_despacho_proto_rawDescData []byte
)

func file_despacho_proto_rawDescGZIP() []byte {
	file_despacho_proto_rawDescOnce.Do(func() {
		file_despacho_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_despacho_proto_rawDesc), len(file_despacho_proto_rawDesc)))
	})
	return file_despacho_proto_rawDescData
}

var file_despacho_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_despacho_proto_goTypes = []any{
	(*DespachoRequest)(nil), // 0: despacho.DespachoRequest
	(*EntregaResponse)(nil), // 1: despacho.EntregaResponse
	(*Guia)(nil),            // 2: despacho.Guia
	(*Producto)(nil),        // 3: despacho.Producto
}
var file_despacho_proto_depIdxs = []int32{
	3, // 0: despacho.Guia.productos:type_name -> despacho.Producto
	2, // 1: despacho.DespachoService.EnviarEntregas:input_type -> despacho.Guia
	0, // 2: despacho.DespachoService.ObtenerDespachos:input_type -> despacho.DespachoRequest
	1, // 3: despacho.DespachoService.EnviarEntregas:output_type -> despacho.EntregaResponse
	2, // 4: despacho.DespachoService.ObtenerDespachos:output_type -> despacho.Guia
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_despacho_proto_init() }
func file_despacho_proto_init() {
	if File_despacho_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_despacho_proto_rawDesc), len(file_despacho_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_despacho_proto_goTypes,
		DependencyIndexes: file_despacho_proto_depIdxs,
		MessageInfos:      file_despacho_proto_msgTypes,
	}.Build()
	File_despacho_proto = out.File
	file_despacho_proto_goTypes = nil
	file_despacho_proto_depIdxs = nil
}
